Eshop-main/Eshop/urls.py
from django.contrib import admin
from django.urls import path  , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('store.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eshop/urls.py
from django.contrib import admin
from django.urls import path  , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('store.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ThirdEye/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mainapp/urls.py
# myapp/urls.py
from django.urls import path,include
from . import views
app_name = 'mainapp'

urlpatterns = [
    path('Index.html', views.home, name='index'),
    path('', views.home, name='home'),
    path('registration.html', views.register, name='register'),
    path('sellerlogin.html', views.sellerlogin, name='sellerlogin'),
    path('login.html', views.login, name='login'),
    path('seller/', include(('seller.urls', 'seller'), namespace='seller')),
]

seller/urls.py
# myapp/urls.py
from django.urls import path,include
from . import views

app_name = 'seller'
urlpatterns = [
    
    path('sellersignup.html', views.sellersignup, name='sellersignup'),
    path('sellerlogin.html', views.sellerlogin, name='sellerlogin'),
    path('SellerHome.html', views.home, name='home'),
]

seller/models.py
# myapp/models.py
from django.db import models

class Province(models.Model):
    Province_Id= models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class City(models.Model):
    City_Id= models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class seller(models.Model):
    User_Id= models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', db_column='User_Id')
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    streetaddress = models.CharField(max_length=255)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=254)
    mobile = models.CharField(max_length=20)

class Login(models.Model):
    User_Id = models.OneToOneField(seller, primary_key=True, on_delete=models.CASCADE,db_column='User_Id')
    username = models.CharField(max_length=150, unique=True)
    password = models.CharField(max_length=128)

'''class category(models.Model):
    category_Id= models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    category_name = models.CharField(max_length=100)
    def __str__(self):
        return self.name'''

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


class addproduct(models.Model):
    # fields of the model
    Product_Id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', db_column='Product_Id')
    product_name = models.CharField(max_length = 100)
    description = models.TextField(max_length = 200)
    price = models.TextField(max_length = 200)
    quantity = models.CharField(max_length=20)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    category =  models.ForeignKey(Category, on_delete=models.CASCADE)

    # renames the instances of the model
    # with their title name
    #def __str__(self):
       # return self.title




    

seller/forms.py
# seller/forms.py
from django import forms
from .models import seller,City, addproduct, Category

class SellerRegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = seller
        city = forms.ModelChoiceField(queryset=City.objects.all(), empty_label='Select City', to_field_name='name')
        fields = ['firstname', 'lastname', 'streetaddress', 'city', 'province', 'zipcode', 'email', 'mobile']
        
class AddProductForm(forms.ModelForm):
    class Meta:
        model = addproduct 
        category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Select Category', to_field_name='category')
        fields = ['product_name', 'description', 'price', 'quantity','category']

seller/views.py
# myapp/views.py
from django.shortcuts import render, redirect
from .forms import SellerRegistrationForm
from django.db import connection
from mainapp.views import sellerlogin
import logging
from django.contrib.auth import authenticate, login


def sellersignup(request):
    if request.method == 'POST':
        form = SellerRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('sellerlogin.html')  # Replace 'login' with your login URL name
    else:
        form = SellerRegistrationForm()
    return render(request, 'sellersignup.html', {'form': form})

def home(request):
    return render(request,'Index.html')

def sellerlogin(request):
    if request.method == 'POST':
        logger = logging.getLogger('seller')
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        logger.debug(f'Attempting login for user: {username}')
        if user is not None:
            logger.info(f'User {username} successfully authenticated.')
            return redirect('SellerHome.html')  # Redirect to the homepage after successful login
        else:
            logger.warning(f'Failed login attempt for user: {username}')
            return render(request, 'sellerlogin.html', {'error_message': 'Invalid credentials'})
    return render(request, 'sellerlogin.html')
  

seller/templates/SellerHome.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

.navbar {
  overflow: hidden;
  background-color: #333;
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;  
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
.topnav a.split {
  float: left;
  background-color: #04AA6D;
  color: white;
}
.login {
  float: right;
  
  color: white;
}
</style>
</head>
<body style="background-color:white;">

<div class="navbar topnav">
  <a href="#" class="split">ThirdEye</a>
  <a href="Index.html">Home</a>
  <div class="dropdown">
    <button class="dropbtn">Registration 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="registration.html">User</a>
      <a href="{% url 'seller:sellersignup' %}">Seller</a>
    </div>
  </div> 
   <div class="dropdown login">
    <button class="dropbtn"><i class="fa fa-fw fa-user"></i>Login 
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="login.html">User</a>
      <a href="sellerlogin.html">Seller</a>
    </div>
  </div> 
</div>

<div style="padding-left:16px">

</div>

</body>
</html>

seller/templates/addproduct.html
<form method="POST" enctype="multipart/form-data">

	<!-- Security token -->
	{% csrf_token %}

	<!-- Using the formset -->
	{{ form.as_p }}
	
	<input type="submit" value="Submit">
</form>

seller/templates/sellersignup.html
<!-- myapp/templates/registration/register.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Thirdeye| Seller SignUp</title>
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/styles.css' %}">

    <style>
        /* static/mainapp/styles.css */

/* Style the form elements */
form {
    margin: 20px;
  }
  
  label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
  }
  
  input, select {
    width: 100%;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
  }
  
  input[type="submit"] {
    background-color: #007BFF;
    color: #fff;
    cursor: pointer;
  }
  
  .registerbtn {
    background-color: #04AA6D;
    color: white;
    padding: 16px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
  }
  .signin {
    background-color: #f1f1f1;
    text-align: center;
  }
  .registerbtn:hover {
    opacity: 1;
  }

  a {
    color: dodgerblue;
  }
  
  input:focus, select:focus {
    background-color: #ddd;
    outline: none;
  }

  body {
    font-family: Arial, Helvetica, sans-serif;
    
  }
  
  * {
    box-sizing: border-box;
  }
  
  /* Add padding to containers */
  .container {
    padding: 16px;
    background-color: white;
  }

  .form-center {
    width: 50%;
    background-color: whitesmoke;
   
    border-radius: 10px;
    margin: auto;
  }
  
  /* Add more CSS rules as needed for styling */
  
    </style>
</head>
<body>
    <center><h2>SELLER REGISTRATION</h2></center>
    <div class="form-center">
    
    <form method="post" class="form-center">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="registerbtn">Register</button>
        <div class="container signin">
           
            <p>Already have an account? <a href="{% url 'mainapp:sellerlogin' %}">Sign in</a>.</p>
            
        </div>
    </form>
</div>
</body>
</html>